<?php
$productList = $this->getList();
$data = $productList->getData();
?>


<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
            <tr class="headings">
                <th class="col-product"><span>Product</span></th>
                <th class="col-product"><span>Quantity</span></th>
                <th class="col-price-original"><span>Product Price</span></th>
                <th class="col-price"><span>Proposed Price</span></th>
            </tr>
        </thead>
        <tbody class="even">
            <?php foreach ($data as $list): ?>
                <tr>
                    <td class="col-product"><div id="order_item_2">
                            <div id="order_item_2_title" class="product-title">
                                Minerva LumaTech™ V-Tee-XS-Blue   
                            </div>
                        </div>
                    </td>
                    <td><?php echo $list['qty']; ?></td>
                    <td class="col-status"><?php echo $this->priceFormat($list['product_price']); ?></td>
                    <td class="col-price-original"><span class="price"><?php echo $this->priceFormat($list['proposed_price']); ?></span></td>
                </tr>
            <?php endforeach; ?>

        </tbody>
    </table>
</div>